// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: k8s_rpc.proto

package server

import (
	"context"

	"k8s_rpc/internal/logic"
	"k8s_rpc/internal/svc"
	"k8s_rpc/k8s_rpc"
)

type K8sRpcServer struct {
	svcCtx *svc.ServiceContext
	k8s_rpc.UnimplementedK8SRpcServer
}

func NewK8sRpcServer(svcCtx *svc.ServiceContext) *K8sRpcServer {
	return &K8sRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *K8sRpcServer) Ping(ctx context.Context, in *k8s_rpc.Request) (*k8s_rpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
