// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: tree_rpc.proto

package server

import (
	"context"

	"tree_rpc/internal/logic"
	"tree_rpc/internal/svc"
	"tree_rpc/tree_rpc"
)

type TreeRpcServer struct {
	svcCtx *svc.ServiceContext
	tree_rpc.UnimplementedTreeRpcServer
}

func NewTreeRpcServer(svcCtx *svc.ServiceContext) *TreeRpcServer {
	return &TreeRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *TreeRpcServer) Ping(ctx context.Context, in *tree_rpc.Request) (*tree_rpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
