// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: aicoreops_cicd.proto

package server

import (
	"context"

	"github.com/GoSimplicity/AICoreOps/services/aicoreops_cicd/aicoreops_cicd"
	"github.com/GoSimplicity/AICoreOps/services/aicoreops_cicd/internal/logic"
	"github.com/GoSimplicity/AICoreOps/services/aicoreops_cicd/internal/svc"
)

type AicoreopsCicdServer struct {
	svcCtx *svc.ServiceContext
	aicoreops_cicd.UnimplementedAicoreopsCicdServer
}

func NewAicoreopsCicdServer(svcCtx *svc.ServiceContext) *AicoreopsCicdServer {
	return &AicoreopsCicdServer{
		svcCtx: svcCtx,
	}
}

func (s *AicoreopsCicdServer) Ping(ctx context.Context, in *aicoreops_cicd.Request) (*aicoreops_cicd.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
