// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: tree_rpc.proto

package tree_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	TreeRpc_Ping_FullMethodName = "/tree_rpc.Tree_rpc/Ping"
)

// TreeRpcClient is the client API for TreeRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TreeRpcClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type treeRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewTreeRpcClient(cc grpc.ClientConnInterface) TreeRpcClient {
	return &treeRpcClient{cc}
}

func (c *treeRpcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, TreeRpc_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TreeRpcServer is the server API for TreeRpc service.
// All implementations must embed UnimplementedTreeRpcServer
// for forward compatibility
type TreeRpcServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedTreeRpcServer()
}

// UnimplementedTreeRpcServer must be embedded to have forward compatible implementations.
type UnimplementedTreeRpcServer struct {
}

func (UnimplementedTreeRpcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedTreeRpcServer) mustEmbedUnimplementedTreeRpcServer() {}

// UnsafeTreeRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TreeRpcServer will
// result in compilation errors.
type UnsafeTreeRpcServer interface {
	mustEmbedUnimplementedTreeRpcServer()
}

func RegisterTreeRpcServer(s grpc.ServiceRegistrar, srv TreeRpcServer) {
	s.RegisterService(&TreeRpc_ServiceDesc, srv)
}

func _TreeRpc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeRpcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeRpc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeRpcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// TreeRpc_ServiceDesc is the grpc.ServiceDesc for TreeRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TreeRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tree_rpc.Tree_rpc",
	HandlerType: (*TreeRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _TreeRpc_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tree_rpc.proto",
}
