// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: aicoreops_workorder.proto

package server

import (
	"context"

	"aicoreops_workorder/aicoreops_workorder"
	"aicoreops_workorder/internal/logic"
	"aicoreops_workorder/internal/svc"
)

type AicoreopsWorkorderServer struct {
	svcCtx *svc.ServiceContext
	aicoreops_workorder.UnimplementedAicoreopsWorkorderServer
}

func NewAicoreopsWorkorderServer(svcCtx *svc.ServiceContext) *AicoreopsWorkorderServer {
	return &AicoreopsWorkorderServer{
		svcCtx: svcCtx,
	}
}

func (s *AicoreopsWorkorderServer) Ping(ctx context.Context, in *aicoreops_workorder.Request) (*aicoreops_workorder.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
