// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: aicoreops_prometheus.proto

package aicoreops_prometheus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AicoreopsPrometheus_Ping_FullMethodName = "/aicoreops_prometheus.Aicoreops_prometheus/Ping"
)

// AicoreopsPrometheusClient is the client API for AicoreopsPrometheus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AicoreopsPrometheusClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type aicoreopsPrometheusClient struct {
	cc grpc.ClientConnInterface
}

func NewAicoreopsPrometheusClient(cc grpc.ClientConnInterface) AicoreopsPrometheusClient {
	return &aicoreopsPrometheusClient{cc}
}

func (c *aicoreopsPrometheusClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, AicoreopsPrometheus_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AicoreopsPrometheusServer is the server API for AicoreopsPrometheus service.
// All implementations must embed UnimplementedAicoreopsPrometheusServer
// for forward compatibility
type AicoreopsPrometheusServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedAicoreopsPrometheusServer()
}

// UnimplementedAicoreopsPrometheusServer must be embedded to have forward compatible implementations.
type UnimplementedAicoreopsPrometheusServer struct {
}

func (UnimplementedAicoreopsPrometheusServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAicoreopsPrometheusServer) mustEmbedUnimplementedAicoreopsPrometheusServer() {}

// UnsafeAicoreopsPrometheusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AicoreopsPrometheusServer will
// result in compilation errors.
type UnsafeAicoreopsPrometheusServer interface {
	mustEmbedUnimplementedAicoreopsPrometheusServer()
}

func RegisterAicoreopsPrometheusServer(s grpc.ServiceRegistrar, srv AicoreopsPrometheusServer) {
	s.RegisterService(&AicoreopsPrometheus_ServiceDesc, srv)
}

func _AicoreopsPrometheus_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AicoreopsPrometheusServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AicoreopsPrometheus_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AicoreopsPrometheusServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// AicoreopsPrometheus_ServiceDesc is the grpc.ServiceDesc for AicoreopsPrometheus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AicoreopsPrometheus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aicoreops_prometheus.Aicoreops_prometheus",
	HandlerType: (*AicoreopsPrometheusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AicoreopsPrometheus_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aicoreops_prometheus.proto",
}
