// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: aicoreops_tree.proto

package client

import (
	"context"

	"aicoreops_tree/types"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = types.Request
	Response = types.Response

	AicoreopsTree interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultAicoreopsTree struct {
		cli zrpc.Client
	}
)

func NewAicoreopsTree(cli zrpc.Client) AicoreopsTree {
	return &defaultAicoreopsTree{
		cli: cli,
	}
}

func (m *defaultAicoreopsTree) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := types.NewAicoreopsTreeClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
