// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: aicoreops_cicd.proto

package aicoreops_cicd

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AicoreopsCicd_Ping_FullMethodName = "/aicoreops_cicd.Aicoreops_cicd/Ping"
)

// AicoreopsCicdClient is the client API for AicoreopsCicd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AicoreopsCicdClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type aicoreopsCicdClient struct {
	cc grpc.ClientConnInterface
}

func NewAicoreopsCicdClient(cc grpc.ClientConnInterface) AicoreopsCicdClient {
	return &aicoreopsCicdClient{cc}
}

func (c *aicoreopsCicdClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, AicoreopsCicd_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AicoreopsCicdServer is the server API for AicoreopsCicd service.
// All implementations must embed UnimplementedAicoreopsCicdServer
// for forward compatibility
type AicoreopsCicdServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedAicoreopsCicdServer()
}

// UnimplementedAicoreopsCicdServer must be embedded to have forward compatible implementations.
type UnimplementedAicoreopsCicdServer struct {
}

func (UnimplementedAicoreopsCicdServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAicoreopsCicdServer) mustEmbedUnimplementedAicoreopsCicdServer() {}

// UnsafeAicoreopsCicdServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AicoreopsCicdServer will
// result in compilation errors.
type UnsafeAicoreopsCicdServer interface {
	mustEmbedUnimplementedAicoreopsCicdServer()
}

func RegisterAicoreopsCicdServer(s grpc.ServiceRegistrar, srv AicoreopsCicdServer) {
	s.RegisterService(&AicoreopsCicd_ServiceDesc, srv)
}

func _AicoreopsCicd_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AicoreopsCicdServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AicoreopsCicd_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AicoreopsCicdServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// AicoreopsCicd_ServiceDesc is the grpc.ServiceDesc for AicoreopsCicd service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AicoreopsCicd_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aicoreops_cicd.Aicoreops_cicd",
	HandlerType: (*AicoreopsCicdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AicoreopsCicd_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aicoreops_cicd.proto",
}
