// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: role_rpc.proto

package server

import (
	"context"

	"role_rpc/internal/logic"
	"role_rpc/internal/svc"
	"role_rpc/role_rpc"
)

type RoleRpcServer struct {
	svcCtx *svc.ServiceContext
	role_rpc.UnimplementedRoleRpcServer
}

func NewRoleRpcServer(svcCtx *svc.ServiceContext) *RoleRpcServer {
	return &RoleRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RoleRpcServer) Ping(ctx context.Context, in *role_rpc.Request) (*role_rpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
