// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: aicoreops_role.proto

package types

import (
	"context"

	"aicoreops_role/types"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = aicoreops_role.Request
	Response = aicoreops_role.Response

	AicoreopsRole interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultAicoreopsRole struct {
		cli zrpc.Client
	}
)

func NewAicoreopsRole(cli zrpc.Client) AicoreopsRole {
	return &defaultAicoreopsRole{
		cli: cli,
	}
}

func (m *defaultAicoreopsRole) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := aicoreops_role.NewAicoreopsRoleClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
