// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: aicoreops_ai.proto

package client
	"github.com/GoSimplicity/AICoreOps/services/aicoreops_ai/types"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = types.Request
	Response = types.Response

	AicoreopsAi interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultAicoreopsAi struct {
		cli zrpc.Client
	}
)

func NewAicoreopsAi(cli zrpc.Client) AicoreopsAi {
	return &defaultAicoreopsAi{
		cli: cli,
	}
}

func (m *defaultAicoreopsAi) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := types.NewAicoreopsAiClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

