// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: prometheus_rpc.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertmanagerPool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                    int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AlertmanagerInstances []string `protobuf:"bytes,3,rep,name=alertmanager_instances,json=alertmanagerInstances,proto3" json:"alertmanager_instances,omitempty"`
	UserId                int64    `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResolveTimeout        string   `protobuf:"bytes,5,opt,name=resolve_timeout,json=resolveTimeout,proto3" json:"resolve_timeout,omitempty"`
	GroupWait             string   `protobuf:"bytes,6,opt,name=group_wait,json=groupWait,proto3" json:"group_wait,omitempty"`
	GroupInterval         string   `protobuf:"bytes,7,opt,name=group_interval,json=groupInterval,proto3" json:"group_interval,omitempty"`
	RepeatInterval        string   `protobuf:"bytes,8,opt,name=repeat_interval,json=repeatInterval,proto3" json:"repeat_interval,omitempty"`
	GroupBy               []string `protobuf:"bytes,9,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	Receiver              string   `protobuf:"bytes,10,opt,name=receiver,proto3" json:"receiver,omitempty"`
}

func (x *AlertmanagerPool) Reset() {
	*x = AlertmanagerPool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prometheus_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertmanagerPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertmanagerPool) ProtoMessage() {}

func (x *AlertmanagerPool) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertmanagerPool.ProtoReflect.Descriptor instead.
func (*AlertmanagerPool) Descriptor() ([]byte, []int) {
	return file_prometheus_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *AlertmanagerPool) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AlertmanagerPool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertmanagerPool) GetAlertmanagerInstances() []string {
	if x != nil {
		return x.AlertmanagerInstances
	}
	return nil
}

func (x *AlertmanagerPool) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AlertmanagerPool) GetResolveTimeout() string {
	if x != nil {
		return x.ResolveTimeout
	}
	return ""
}

func (x *AlertmanagerPool) GetGroupWait() string {
	if x != nil {
		return x.GroupWait
	}
	return ""
}

func (x *AlertmanagerPool) GetGroupInterval() string {
	if x != nil {
		return x.GroupInterval
	}
	return ""
}

func (x *AlertmanagerPool) GetRepeatInterval() string {
	if x != nil {
		return x.RepeatInterval
	}
	return ""
}

func (x *AlertmanagerPool) GetGroupBy() []string {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *AlertmanagerPool) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type GetAlertmanagerPoolListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAlertmanagerPoolListRequest) Reset() {
	*x = GetAlertmanagerPoolListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prometheus_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAlertmanagerPoolListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertmanagerPoolListRequest) ProtoMessage() {}

func (x *GetAlertmanagerPoolListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertmanagerPoolListRequest.ProtoReflect.Descriptor instead.
func (*GetAlertmanagerPoolListRequest) Descriptor() ([]byte, []int) {
	return file_prometheus_rpc_proto_rawDescGZIP(), []int{1}
}

type GetAlertmanagerPoolListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*AlertmanagerPool `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAlertmanagerPoolListResponse) Reset() {
	*x = GetAlertmanagerPoolListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prometheus_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAlertmanagerPoolListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertmanagerPoolListResponse) ProtoMessage() {}

func (x *GetAlertmanagerPoolListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertmanagerPoolListResponse.ProtoReflect.Descriptor instead.
func (*GetAlertmanagerPoolListResponse) Descriptor() ([]byte, []int) {
	return file_prometheus_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetAlertmanagerPoolListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAlertmanagerPoolListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAlertmanagerPoolListResponse) GetData() []*AlertmanagerPool {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateMonitorAlertManagerPoolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pool *AlertmanagerPool `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
}

func (x *CreateMonitorAlertManagerPoolRequest) Reset() {
	*x = CreateMonitorAlertManagerPoolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prometheus_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMonitorAlertManagerPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMonitorAlertManagerPoolRequest) ProtoMessage() {}

func (x *CreateMonitorAlertManagerPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMonitorAlertManagerPoolRequest.ProtoReflect.Descriptor instead.
func (*CreateMonitorAlertManagerPoolRequest) Descriptor() ([]byte, []int) {
	return file_prometheus_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMonitorAlertManagerPoolRequest) GetPool() *AlertmanagerPool {
	if x != nil {
		return x.Pool
	}
	return nil
}

type CreateMonitorAlertManagerPoolResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateMonitorAlertManagerPoolResponse) Reset() {
	*x = CreateMonitorAlertManagerPoolResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prometheus_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMonitorAlertManagerPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMonitorAlertManagerPoolResponse) ProtoMessage() {}

func (x *CreateMonitorAlertManagerPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMonitorAlertManagerPoolResponse.ProtoReflect.Descriptor instead.
func (*CreateMonitorAlertManagerPoolResponse) Descriptor() ([]byte, []int) {
	return file_prometheus_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMonitorAlertManagerPoolResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateMonitorAlertManagerPoolResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateMonitorAlertManagerPoolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateMonitorAlertManagerPoolRequest) Reset() {
	*x = UpdateMonitorAlertManagerPoolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prometheus_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMonitorAlertManagerPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMonitorAlertManagerPoolRequest) ProtoMessage() {}

func (x *UpdateMonitorAlertManagerPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMonitorAlertManagerPoolRequest.ProtoReflect.Descriptor instead.
func (*UpdateMonitorAlertManagerPoolRequest) Descriptor() ([]byte, []int) {
	return file_prometheus_rpc_proto_rawDescGZIP(), []int{5}
}

type UpdateMonitorAlertManagerPoolResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateMonitorAlertManagerPoolResponse) Reset() {
	*x = UpdateMonitorAlertManagerPoolResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prometheus_rpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMonitorAlertManagerPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMonitorAlertManagerPoolResponse) ProtoMessage() {}

func (x *UpdateMonitorAlertManagerPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_rpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMonitorAlertManagerPoolResponse.ProtoReflect.Descriptor instead.
func (*UpdateMonitorAlertManagerPoolResponse) Descriptor() ([]byte, []int) {
	return file_prometheus_rpc_proto_rawDescGZIP(), []int{6}
}

type DeleteMonitorAlertManagerPoolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMonitorAlertManagerPoolRequest) Reset() {
	*x = DeleteMonitorAlertManagerPoolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prometheus_rpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMonitorAlertManagerPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMonitorAlertManagerPoolRequest) ProtoMessage() {}

func (x *DeleteMonitorAlertManagerPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_rpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMonitorAlertManagerPoolRequest.ProtoReflect.Descriptor instead.
func (*DeleteMonitorAlertManagerPoolRequest) Descriptor() ([]byte, []int) {
	return file_prometheus_rpc_proto_rawDescGZIP(), []int{7}
}

type DeleteMonitorAlertManagerPoolResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMonitorAlertManagerPoolResponse) Reset() {
	*x = DeleteMonitorAlertManagerPoolResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prometheus_rpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMonitorAlertManagerPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMonitorAlertManagerPoolResponse) ProtoMessage() {}

func (x *DeleteMonitorAlertManagerPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prometheus_rpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMonitorAlertManagerPoolResponse.ProtoReflect.Descriptor instead.
func (*DeleteMonitorAlertManagerPoolResponse) Descriptor() ([]byte, []int) {
	return file_prometheus_rpc_proto_rawDescGZIP(), []int{8}
}

var File_prometheus_rpc_proto protoreflect.FileDescriptor

var file_prometheus_rpc_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x5f, 0x72, 0x70, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65,
	0x75, 0x73, 0x5f, 0x72, 0x70, 0x63, 0x22, 0xd5, 0x02, 0x0a, 0x10, 0x41, 0x6c, 0x65, 0x72, 0x74,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x35, 0x0a, 0x16, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x5f,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x15, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x27, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x77, 0x61, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x57, 0x61, 0x69, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x27,
	0x0a, 0x0f, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61,
	0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x62, 0x79, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x42, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x22, 0x20,
	0x0a, 0x1e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x85, 0x01, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x5f, 0x72, 0x70,
	0x63, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x6f,
	0x6f, 0x6c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5c, 0x0a, 0x24, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x34, 0x0a, 0x04, 0x70, 0x6f, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x5f, 0x72, 0x70, 0x63, 0x2e,
	0x41, 0x6c, 0x65, 0x72, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c,
	0x52, 0x04, 0x70, 0x6f, 0x6f, 0x6c, 0x22, 0x55, 0x0a, 0x25, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x26, 0x0a,
	0x24, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x41, 0x6c,
	0x65, 0x72, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x27, 0x0a, 0x25, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26,
	0x0a, 0x24, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x41,
	0x6c, 0x65, 0x72, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x27, 0x0a, 0x25, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0xb9, 0x04, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x5f, 0x72,
	0x70, 0x63, 0x12, 0x7a, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e, 0x2e,
	0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x6f,
	0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e,
	0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x6f,
	0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x8c,
	0x01, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x41, 0x6c, 0x65, 0x72, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c,
	0x12, 0x34, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x5f, 0x72, 0x70,
	0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x41,
	0x6c, 0x65, 0x72, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68,
	0x65, 0x75, 0x73, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f,
	0x6e, 0x69, 0x74, 0x6f, 0x72, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x8c, 0x01,
	0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x41,
	0x6c, 0x65, 0x72, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x12,
	0x34, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x5f, 0x72, 0x70, 0x63,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x41, 0x6c,
	0x65, 0x72, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65,
	0x75, 0x73, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x8c, 0x01, 0x0a,
	0x1d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x41, 0x6c,
	0x65, 0x72, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x34,
	0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x5f, 0x72, 0x70, 0x63, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75,
	0x73, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50,
	0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prometheus_rpc_proto_rawDescOnce sync.Once
	file_prometheus_rpc_proto_rawDescData = file_prometheus_rpc_proto_rawDesc
)

func file_prometheus_rpc_proto_rawDescGZIP() []byte {
	file_prometheus_rpc_proto_rawDescOnce.Do(func() {
		file_prometheus_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_prometheus_rpc_proto_rawDescData)
	})
	return file_prometheus_rpc_proto_rawDescData
}

var file_prometheus_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_prometheus_rpc_proto_goTypes = []any{
	(*AlertmanagerPool)(nil),                      // 0: prometheus_rpc.AlertmanagerPool
	(*GetAlertmanagerPoolListRequest)(nil),        // 1: prometheus_rpc.GetAlertmanagerPoolListRequest
	(*GetAlertmanagerPoolListResponse)(nil),       // 2: prometheus_rpc.GetAlertmanagerPoolListResponse
	(*CreateMonitorAlertManagerPoolRequest)(nil),  // 3: prometheus_rpc.CreateMonitorAlertManagerPoolRequest
	(*CreateMonitorAlertManagerPoolResponse)(nil), // 4: prometheus_rpc.CreateMonitorAlertManagerPoolResponse
	(*UpdateMonitorAlertManagerPoolRequest)(nil),  // 5: prometheus_rpc.UpdateMonitorAlertManagerPoolRequest
	(*UpdateMonitorAlertManagerPoolResponse)(nil), // 6: prometheus_rpc.UpdateMonitorAlertManagerPoolResponse
	(*DeleteMonitorAlertManagerPoolRequest)(nil),  // 7: prometheus_rpc.DeleteMonitorAlertManagerPoolRequest
	(*DeleteMonitorAlertManagerPoolResponse)(nil), // 8: prometheus_rpc.DeleteMonitorAlertManagerPoolResponse
}
var file_prometheus_rpc_proto_depIdxs = []int32{
	0, // 0: prometheus_rpc.GetAlertmanagerPoolListResponse.data:type_name -> prometheus_rpc.AlertmanagerPool
	0, // 1: prometheus_rpc.CreateMonitorAlertManagerPoolRequest.pool:type_name -> prometheus_rpc.AlertmanagerPool
	1, // 2: prometheus_rpc.Prometheus_rpc.GetAlertmanagerPoolList:input_type -> prometheus_rpc.GetAlertmanagerPoolListRequest
	3, // 3: prometheus_rpc.Prometheus_rpc.CreateMonitorAlertManagerPool:input_type -> prometheus_rpc.CreateMonitorAlertManagerPoolRequest
	5, // 4: prometheus_rpc.Prometheus_rpc.UpdateMonitorAlertManagerPool:input_type -> prometheus_rpc.UpdateMonitorAlertManagerPoolRequest
	7, // 5: prometheus_rpc.Prometheus_rpc.DeleteMonitorAlertManagerPool:input_type -> prometheus_rpc.DeleteMonitorAlertManagerPoolRequest
	2, // 6: prometheus_rpc.Prometheus_rpc.GetAlertmanagerPoolList:output_type -> prometheus_rpc.GetAlertmanagerPoolListResponse
	4, // 7: prometheus_rpc.Prometheus_rpc.CreateMonitorAlertManagerPool:output_type -> prometheus_rpc.CreateMonitorAlertManagerPoolResponse
	6, // 8: prometheus_rpc.Prometheus_rpc.UpdateMonitorAlertManagerPool:output_type -> prometheus_rpc.UpdateMonitorAlertManagerPoolResponse
	8, // 9: prometheus_rpc.Prometheus_rpc.DeleteMonitorAlertManagerPool:output_type -> prometheus_rpc.DeleteMonitorAlertManagerPoolResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_prometheus_rpc_proto_init() }
func file_prometheus_rpc_proto_init() {
	if File_prometheus_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prometheus_rpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AlertmanagerPool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prometheus_rpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetAlertmanagerPoolListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prometheus_rpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetAlertmanagerPoolListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prometheus_rpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateMonitorAlertManagerPoolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prometheus_rpc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreateMonitorAlertManagerPoolResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prometheus_rpc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMonitorAlertManagerPoolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prometheus_rpc_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMonitorAlertManagerPoolResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prometheus_rpc_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteMonitorAlertManagerPoolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prometheus_rpc_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteMonitorAlertManagerPoolResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prometheus_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prometheus_rpc_proto_goTypes,
		DependencyIndexes: file_prometheus_rpc_proto_depIdxs,
		MessageInfos:      file_prometheus_rpc_proto_msgTypes,
	}.Build()
	File_prometheus_rpc_proto = out.File
	file_prometheus_rpc_proto_rawDesc = nil
	file_prometheus_rpc_proto_goTypes = nil
	file_prometheus_rpc_proto_depIdxs = nil
}
