// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: tree_rpc.proto

package treerpcclient

import (
	"context"

	"tree_rpc/tree_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = tree_rpc.Request
	Response = tree_rpc.Response

	TreeRpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultTreeRpc struct {
		cli zrpc.Client
	}
)

func NewTreeRpc(cli zrpc.Client) TreeRpc {
	return &defaultTreeRpc{
		cli: cli,
	}
}

func (m *defaultTreeRpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := tree_rpc.NewTreeRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
