// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: aicoreops_prometheus.proto

package server

import (
	"github.com/GoSimplicity/AICoreOps/services/aicoreops_prometheus/types"
	"github.com/GoSimplicity/AICoreOps/services/aicoreops_prometheus/internal/svc"
)

type AicoreopsPrometheusServer struct {
	svcCtx *svc.ServiceContext
	types.UnimplementedPrometheusRpcServer
}

func NewAicoreopsPrometheusServer(svcCtx *svc.ServiceContext) *AicoreopsPrometheusServer {
	return &AicoreopsPrometheusServer{
		svcCtx: svcCtx,
	}
}

