// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: aicoreops_job.proto

package aicoreops_job

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AicoreopsJob_Ping_FullMethodName = "/aicoreops_job.Aicoreops_job/Ping"
)

// AicoreopsJobClient is the client API for AicoreopsJob service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AicoreopsJobClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type aicoreopsJobClient struct {
	cc grpc.ClientConnInterface
}

func NewAicoreopsJobClient(cc grpc.ClientConnInterface) AicoreopsJobClient {
	return &aicoreopsJobClient{cc}
}

func (c *aicoreopsJobClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, AicoreopsJob_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AicoreopsJobServer is the server API for AicoreopsJob service.
// All implementations must embed UnimplementedAicoreopsJobServer
// for forward compatibility
type AicoreopsJobServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedAicoreopsJobServer()
}

// UnimplementedAicoreopsJobServer must be embedded to have forward compatible implementations.
type UnimplementedAicoreopsJobServer struct {
}

func (UnimplementedAicoreopsJobServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAicoreopsJobServer) mustEmbedUnimplementedAicoreopsJobServer() {}

// UnsafeAicoreopsJobServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AicoreopsJobServer will
// result in compilation errors.
type UnsafeAicoreopsJobServer interface {
	mustEmbedUnimplementedAicoreopsJobServer()
}

func RegisterAicoreopsJobServer(s grpc.ServiceRegistrar, srv AicoreopsJobServer) {
	s.RegisterService(&AicoreopsJob_ServiceDesc, srv)
}

func _AicoreopsJob_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AicoreopsJobServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AicoreopsJob_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AicoreopsJobServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// AicoreopsJob_ServiceDesc is the grpc.ServiceDesc for AicoreopsJob service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AicoreopsJob_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aicoreops_job.Aicoreops_job",
	HandlerType: (*AicoreopsJobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AicoreopsJob_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aicoreops_job.proto",
}
